//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_DOWN                        164
#define IDB_BITMAP6                     166
#define IDB_MACHINEGUN_                 166
#define IDB_MACHINEGUN_RIGHT            166
#define IDB_BITMAP3                     167
#define IDB_BULLET                      167
#define IDB_SIDE                        168
#define IDB_SIDE1                       168
#define IDB_BITMAP5                     169
#define IDB_MONSTER1                    172
#define IDB_MONSTER2                    173
#define IDB_MONSTER3                    174
#define IDB_MONSTER4                    175
#define IDB_MONSTER5                    176
#define IDB_MONSTER6                    177
#define IDB_MONSTER7                    178
#define IDB_BITMAP13                    179
#define IDB_MONSTER8                    179
#define IDB_BITMAP9                     183
#define IDB_PNG1                        189
#define IDB_PNG2                        190
#define IDB_PNG3                        191
#define IDB_PNG4                        192
#define IDB_BITMAP10                    196
#define IDB_M_EXPLODE1                  197
#define IDB_M_EXPLODE2                  198
#define IDB_M_EXPLODE3                  199
#define IDB_BITMAP4                     200
#define IDB_BITMAP7                     201
#define IDB_BITMAP8                     202
#define IDB_PNG5                        203
#define IDB_BITMAP11                    204
#define IDB_GUN                         204
#define IDB_BITMAP12                    205
#define IDB_LANDMINE                    205
#define IDB_BITMAP14                    206
#define IDB_MAP                         206
#define IDB_BITMAP15                    207
#define IDB_BITMAP16                    217
#define IDB_BASE                        218
#define IDB_DIAMOND1                    219
#define IDB_DIAMIND2                    220
#define IDB_DIAMOND2                    220
#define IDB_DIAMOND3                    221
#define IDB_DIAMOND4                    222
#define IDB_COIN1                       223
#define IDB_COIN2                       224
#define IDB_COIN3                       225
#define IDB_COIN4                       226
#define IDB_COIN5                       227
#define IDB_SHOTGUN2                    228
#define IDB_SHOTGUN3                    229
#define IDB_SHOTGUN4                    230
#define IDB_BITMAP20                    231
#define IDB_SHOTGUN1                    231
#define IDB_LANDMINE2                   232
#define IDB_HEAL                        233
#define IDB_HEAL2                       234
#define IDB_HEAL3                       235
#define IDB_BITMAP21                    236
#define IDB_HEAL4                       236
#define IDB_MINEBOOM                    237
#define IDB_MINEBOOM2                   238
#define IDB_MINEBOOM3                   239
#define IDB_MINEBOOM4                   240
#define IDB_BITMAP23                    241
#define IDB_MINEBOOM5                   241
#define IDB_GASBOOM1                    242
#define IDB_GASBOOM2                    243
#define IDB_GASBOOM3                    244
#define IDB_GASBOOM4                    245
#define IDB_GASBOOM5                    246
#define IDB_GASBOOM6                    247
#define IDB_BITMAP26                    248
#define IDB_GASBOOM7                    248
#define IDB_GASONLINE                   249
#define IDB_DOWN1                       250
#define IDB_DOWN2                       251
#define IDB_DOWN3                       252
#define IDB_DOWN4                       253
#define IDB_LSIDE1                      254
#define IDB_LSIDE2                      255
#define IDB_LSIDE3                      256
#define IDB_LSIDE4                      257
#define IDB_SIDE3                       260
#define IDB_SIDE4                       261
#define IDB_SIDE2                       262
#define IDB_UP1                         263
#define IDB_UP2                         264
#define IDB_UP3                         265
#define IDB_BITMAP24                    266
#define IDB_UP4                         266
#define IDB_BITMAP31                    276
#define IDB_SHOP                        279
#define IDB_SHOP_MINEB                  280
#define IDB_SHOP_MINE                   281
#define IDB_SHOP_GAS                    282
#define IDB_BITMAP22                    283
#define IDB_SHOP_GASB                   283
#define IDB_SHOP_GAS_INTRO              284
#define IDB_BITMAP18                    285
#define IDB_SHOP_MINE_INTRO             285
#define IDB_INFINITY                    286
#define IDB_STAR                        287
#define IDB_BITMAP17                    288
#define IDB_COINS                       288
#define IDB_MENU                        289
#define IDB_ROCKET2                     290
#define IDB_ROCKET3                     291
#define IDB_ROCKET4                     292
#define IDB_ROCKET1                     293
#define IDB_BITMAP19                    294
#define IDB_ROCKET_BULLET_RIGHT         295
#define IDB_ROCKET_BULLET_DOWN          296
#define IDB_ROCKET_BULLET_LEFT          297
#define IDB_ROCKET_BULLET_UP            298
#define IDB_MACHINEGUN_BULLET_DOWN      299
#define IDB_MACHINEGUN_BULLET_LEFT      300
#define IDB_MACHINEGUN_BULLET_RIGHT     301
#define IDB_MACHINEGUN_BULLET_UP        302
#define IDB_MACHINEGUN_DOWN             303
#define IDB_MACHINEGUN_LEFT             304
#define IDB_MACHINEGUN_UP               306
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        307
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
